if has('vim_starting')
   set nocompatible               
   set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

" Custom bundles
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'bling/vim-airline'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'godlygeek/tabular'
NeoBundle 'plasticboy/vim-markdown'

call neobundle#end()

filetype plugin indent on

" Check for missing bundles
NeoBundleCheck

" Custom settings
syntax on
set expandtab
set shiftwidth=2
set autoindent
set smartindent
set nu
set guioptions-=T

set laststatus=2
set backspace=2
autocmd BufRead,BufNewFile *.md setlocal spell
let g:vim_markdown_initial_foldlevel=2

highlight clear SignColumn
