if has('vim_starting')
   set nocompatible               
   set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

" Custom bundles
NeoBundle 'airblade/vim-gitgutter'
NeoBundle 'bling/vim-airline'
NeoBundle 'kien/ctrlp.vim'
NeoBundle 'godlygeek/tabular'
NeoBundle 'tpope/vim-markdown'
NeoBundle 'reedes/vim-colors-pencil'
NeoBundle 'junegunn/goyo.vim'
NeoBundle 'junegunn/limelight.vim'
NeoBundle 'vim-pandoc/vim-pandoc-syntax'
NeoBundle 'vim-pandoc/vim-pandoc'

call neobundle#end()

filetype plugin indent on
set nocompatible

" Check for missing bundles
NeoBundleCheck

" Custom settings
syntax on
set expandtab
set shiftwidth=2
set autoindent
set smartindent
set nu
set guioptions-=T

set laststatus=2
set backspace=2
autocmd BufRead,BufNewFile *.md setlocal spell

let g:airline_theme = 'pencil'
colorscheme pencil
set background=dark

let g:pandoc#formatting#mode = 'h'

augroup limelight_pencil
    autocmd!
    autocmd ColorScheme * let g:limelight_conceal_ctermfg =
                            \ (&bg == 'dark') ? 'red' : 'darkgray'
augroup END

highlight clear SignColumn
